#服务器端口号
chat:
  server:
    port: 8888

#服务端口号
server:
  port: 8077


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/chat-server?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true